// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHNITWftpBIyWYWBj62JaDO4YJLyL3tHA',
    appId: '1:521292734856:web:e744ccc25b25c9bc47da3d',
    messagingSenderId: '521292734856',
    projectId: 'pic-to-text-cc19f',
    authDomain: 'pic-to-text-cc19f.firebaseapp.com',
    storageBucket: 'pic-to-text-cc19f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOhjn-PyAln4K-E4vEV3tM4cotqTbBj4',
    appId: '1:521292734856:android:590a59a077273c6647da3d',
    messagingSenderId: '521292734856',
    projectId: 'pic-to-text-cc19f',
    storageBucket: 'pic-to-text-cc19f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJF94NyfiB3Yp2Rwc4AdZgUN3E0GjJprA',
    appId: '1:521292734856:ios:a48ab06f3e2a829247da3d',
    messagingSenderId: '521292734856',
    projectId: 'pic-to-text-cc19f',
    storageBucket: 'pic-to-text-cc19f.appspot.com',
    iosBundleId: 'com.example.textRecognitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJF94NyfiB3Yp2Rwc4AdZgUN3E0GjJprA',
    appId: '1:521292734856:ios:5689880a42887beb47da3d',
    messagingSenderId: '521292734856',
    projectId: 'pic-to-text-cc19f',
    storageBucket: 'pic-to-text-cc19f.appspot.com',
    iosBundleId: 'com.example.textRecognitionApp.RunnerTests',
  );
}
